# no version needed since 2020

services:
  jekyll:
    image: bretfisher/jekyll-serve
    command: bundle exec jekyll serve --force_polling --future --draft -H 0.0.0.0 -P 4000
    volumes:
      - ${PWD}:/site
    ports:
      - '4000:4000'